In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/ai_job.csv")

In [ ]:
df = df.drop(['Job ID', "notes","_temp",'data_source'], axis=1, errors='ignore')

In [ ]:
df.head(1)

,JobTitle,Company Size,company_Industry,Country,Remote Type,Exp. Level,Years_Experience,Education Level,Skills - Python,Skills - SQL,Skills - ML,Skills-DeepLearning,skills_Cloud,Salary (USD),Posting Month,posting_Year,Hiring Urgency,Job Openings
0,data_analyst,Start Up,Finance,-,Hybrid,Entry,4,Bachelor,1,FALSE,0,0,0,"$48,629",10,2024,not urgent,1

In [ ]:
df.shape

(10745, 18)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10745 entries, 0 to 10744
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   JobTitle             10352 non-null  object
 1   Company Size         10364 non-null  object
 2   company_Industry     10359 non-null  object
 3   Country              10313 non-null  object
 4   Remote Type          10335 non-null  object
 5   Exp. Level           10355 non-null  object
 6   Years_Experience     10328 non-null  object
 7   Education  Level     10354 non-null  object
 8   Skills - Python      10341 non-null  object
 9   Skills - SQL         10307 non-null  object
 10  Skills - ML          10351 non-null  object
 11  Skills-DeepLearning  10330 non-null  object
 12  skills_Cloud         10361 non-null  object
 13  Salary (USD)         10312 non-null  object
 14  Posting Month        10326 non-null  object
 15  posting_Year         10315 non-null  object
 16  Hiring Urgency       10353 non-null  object
 17  Job Openings         10339 non-null  object
dtypes: object(18)
memory usage: 1.5+ MB

In [ ]:
df.isnull().sum()

JobTitle               393
Company Size           381
company_Industry       386
Country                432
Remote Type            410
Exp. Level             390
Years_Experience       417
Education  Level       391
Skills - Python        404
Skills - SQL           438
Skills - ML            394
Skills-DeepLearning    415
skills_Cloud           384
Salary (USD)           433
Posting Month          419
posting_Year           430
Hiring Urgency         392
Job Openings           406
dtype: int64

In [ ]:
df.replace(['NONE', 'Not Available', 'none', 'NaN', '#N/A', 'nall', 'N/A', 'unknown', 'nan', 'n/a', 'not available', '-', '?', '--', 'Nan', 'Na'], np.nan, inplace=True)

In [ ]:
df.dropna(subset=["JobTitle"], inplace=True)

In [ ]:
df.shape

(10075, 18)

JobTitle -


1.   consistency issues
2.   missing or completeness issues

In [ ]:
df["JobTitle"].isnull().sum()
# df.dropna(subset=["JobTitle"], inplace=True)

np.int64(0)

In [ ]:
df["JobTitle"].fillna('Unknown', inplace=True)

/tmp/ipykernel_11495/3463700150.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["JobTitle"].fillna('Unknown', inplace=True)

In [ ]:
df["JobTitle"] = df["JobTitle"].str.replace(r"[^a-zA-Z]", ' ', regex=True)

In [ ]:
df.sample(5)

,JobTitle,Company Size,company_Industry,Country,Remote Type,Exp. Level,Years_Experience,Education Level,Skills - Python,Skills - SQL,Skills - ML,Skills-DeepLearning,skills_Cloud,Salary (USD),Posting Month,posting_Year,Hiring Urgency,Job Openings
6516,Machine Learning Engineer,Startup,Education,Australi,Remote,Senior,-12,BS,1,1,1,UNKNOWN,0,"$156,231",8,2024,Med,3
553,Business Analyst,Start Up,NaN,germany,office,Entry,5,PhD,0,0,0,0,No,48165,12,2022,High,9
2548,DATA SCIENTIST,MNC,Education,India,Onsite,Senior,-14,PhD,1,1,0,0,1,128406,0,2023,Medium,1
9963,data analyst,STARTUP,IT,Germany,On Site,MID,14,PhD,0,0,0,0,0,79969,12,2025,high,7
2076,Data Analyst,Enterprise,FINANCE,Canada,NaN,Mid-Level,6.2,master's,0,1,0,1,1,99214,2,2025,high,9

In [ ]:
df["JobTitle"] = df["JobTitle"].str.lower().str.strip().str.replace(' ', '')

In [ ]:
df["JobTitle"].unique()

array(['dataanalyst', 'datascientist', 'machinelearningengineer',
       'dataanalst', 'aiengineer', 'bizzanalyst', 'businessanalyst',
       'dataengineer', 'bussinessanalyst', 'bizanalyst', 'nan',
       'dataengneer', 'unknown', 'mlengineer', 'aieng', 'datscientist',
       'machinelerningengineer', 'dataanaylst', 'mleng', 'na',
       'dataengineeer', 'datascienist', 'none', 'null', 'notavailable'],
      dtype=object)

In [ ]:
df["JobTitle"].shape

(10075,)

In [ ]:
mapping = {
    'dataanalyst' : 'Data Analyst',
    'datascientist' : 'Data Scientist',
    'machinelearningengineer' : 'Machine Learning Engineer',
    'dataanalst' : 'Data Analyst',
    'aiengineer' : 'AI Engineer',
    'bizzanalyst' : 'Business Analyst',
    'businessanalyst' : 'Business Analyst',
    'dataengineer' : 'Data Engineer',
    'bussinessanalyst' : 'Business Analyst',
    'bizanalyst': 'Business Analyst',
    'dataengneer': 'Data Engineer',
    'mlengineer' : 'Machine Learning Engineer',
    'aieng' : 'AI Engineer',
    'datscientist': 'Data Scientist',
    '' : 'Unknown',
    'machinelerningengineer' : 'Machine Learning Engineer',
    'dataanaylst' : 'Data Analyst',
    'mleng' : 'Machine Learning Engineer',
    'na': 'Unknown',
    'dataengineeer' : 'Data Engineer',
    'datascienist' : 'Data Scientist',
    'null' : 'Unknown',
    'notavailable' : 'Unknown'
}

df["JobTitle"] = df["JobTitle"].map(mapping)

In [ ]:
df["JobTitle"].value_counts()

JobTitle
Business Analyst             1714
Machine Learning Engineer    1682
AI Engineer                  1679
Data Scientist               1661
Data Analyst                 1626
Data Engineer                1623
Unknown                        40
Name: count, dtype: int64

In [ ]:
df["JobTitle"].shape

(10075,)

Company Size -


1.   consistency issues
2.   missing or completeness issues

In [ ]:
df["Company Size"].isnull().sum()

np.int64(0)

In [ ]:
df["Company Size"].fillna('unknown', inplace=True)
# df["Company Size"].isnull().sum()

/tmp/ipykernel_11495/2773311487.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Company Size"].fillna('unknown', inplace=True)

In [ ]:
df["Company Size"] = df["Company Size"].str.replace(r"[^a-zA-Z]", ' ', regex=True)

In [ ]:
df["Company Size"] = df["Company Size"].str.lower().str.strip().str.replace(' ', '')

In [ ]:
df["Company Size"].unique()

array(['startup', 'enterprise', 'medium', 'unknown', 'mnc', 'enteprise',
       'med', 'multinational', 'enterprize', 'mediumsized', 'na'],
      dtype=object)

In [ ]:
mapping = {
    'startup' : 'Start-up',
    'enterprise' : 'Large',
    'medium' : 'Medium',
    'unknown' : 'Unknown',
    'mnc': 'Large',
    'enteprise' : 'Large',
    'med' : 'Medium',
    'multinational' : 'Large',
    'enterprize' : 'Large',
    'mediumsized': 'Medium',
    '': 'Unknown',
    'na': 'Unknown'
}

df["Company Size"] = df["Company Size"].map(mapping)

In [ ]:
df["Company Size"].value_counts()

Company Size
Large       4672
Start-up    2384
Medium      2289
Unknown      680
Name: count, dtype: int64

company_Industry -


1.  consistency issues
2.  completeness issues

In [ ]:
df["company_Industry"].isnull().sum()

np.int64(0)

In [ ]:
df["company_Industry"].fillna('unknown', inplace=True)
# df["company_Industry"].isnull().sum()

/tmp/ipykernel_11495/686924390.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["company_Industry"].fillna('unknown', inplace=True)

In [ ]:
df["company_Industry"] = df["company_Industry"].str.replace(r"[^a-zA-Z]", ' ', regex=True)

In [ ]:
df["company_Industry"] = df["company_Industry"].str.lower().str.strip().str.replace(' ', '')

In [ ]:
df["company_Industry"].unique()

array(['finance', 'ecommerce', 'retail', 'education', 'technology',
       'retl', 'healthcare', 'educaiton', 'unknown', 'edu', 'retial',
       'it', 'fin', 'fnance', 'financial', 'tech', 'health', 'none', 'na',
       'nan', 'notavailable', 'null'], dtype=object)

In [ ]:
mapping = {
    'finance' : 'Finance',
    'ecommerce' : 'E-commerce',
    'retail' : 'Retail',
    'education': 'Education',
    'technology': 'IT',
    'retl' : 'Retail',
    'healthcare' : 'Healthcare',
    'educaiton' : 'Education',
    '': 'Unknown',
    'edu': 'Education',
    'retial': 'Retail',
    'it': 'IT',
    'fin': 'Finance',
    'fnance': 'Finance',
    'unknown': 'Unknown',
    'financial': 'Finance',
    'tech': 'IT',
    'health': 'Healthcare',
    'none': 'Unknown',
    'na': 'Unknown',
    'nan': 'Unknown',
    'notavailable': 'Unknown',
    'null' : 'Unknown'
}

df["company_Industry"] = df["company_Industry"].map(mapping)

In [ ]:
df["company_Industry"].value_counts()

company_Industry
IT            1611
Finance       1595
E-commerce    1567
Healthcare    1551
Education     1531
Retail        1494
Unknown        676
Name: count, dtype: int64

Country -


1.   consistency issue
2.   completeness issues

In [ ]:
df["Country"].isnull().sum()

np.int64(0)

In [ ]:
df["Country"].fillna('unknown', inplace=True)

/tmp/ipykernel_11495/596139247.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Country"].fillna('unknown', inplace=True)

In [ ]:
df["Country"] = df["Country"].str.replace(r"[^a-zA-Z]", ' ', regex=True)

In [ ]:
df["Country"] = df["Country"].str.lower().str.strip().str.replace(' ', '')

In [ ]:
df["Country"].unique()

array(['unknown', 'unitedkingdom', 'singapore', 'canda', 'germny',
       'germany', 'uk', 'australia', 'usa', 'canada', 'bharat', 'india',
       'inda', 'aus', 'na', 'in', 'australi', 'deutschland', 'can',
       'greatbritain', 'sg', 'aussie', 'unitedstates', 'singpore', 'de',
       'us', 'britain', 'sgp', 'singapor', 'null', 'notavailable', 'none',
       'nan'], dtype=object)

In [ ]:
mapping = {
    'unknown': 'Unknown',
    'unitedkingdom': 'United Kingdom',
    'singapore': 'Singapore',
    'canda' : 'Canada',
    'germny': 'Germany',
    'germany': 'Germany',
    'uk' : 'United Kingdom',
    'australia' : 'Australia',
    'usa' : 'United State America',
    'canada' : 'Canada',
    'bharat': 'India',
    'india': 'India',
    'inda': 'India',
    'aus' : 'Australia',
    'na': 'Unknown',
    'in': 'India',
    'australi' : 'Australia',
    'deutschland' : 'Germany',
    '' : 'Unknown',
    'can': 'Canada',
    'greatbritain' : 'United Kingdom',
    'sg': 'Singapore',
    'aussie': 'Australia',
    'unitedstates': 'United State America',
    'singpore': 'Singapore',
    'de': 'United State America',
    'us' : 'United State America',
    'britain': 'United Kingdom',
    'sgp': 'Singapore',
    'singapor': 'Singapore',
    'null': 'Unknown',
    'notavailable': 'Unknown',
    'none': 'Unknown',
    'nan' : 'Unknown'
}

In [ ]:
df["Country"] = df["Country"].map(mapping)

In [ ]:
df["Country"].value_counts()

Country
United State America    1417
Singapore               1352
United Kingdom          1342
India                   1318
Canada                  1315
Australia               1310
Germany                 1256
Unknown                  715
Name: count, dtype: int64

In [ ]:
df["Country"].isnull().sum()

np.int64(0)

Remote Type -


1.   consistency issues
2.   completeness issues
3. abbreviation issues

In [ ]:
df['Remote Type'].isnull().sum()

np.int64(0)

In [ ]:
df['Remote Type'].fillna('unknown', inplace=True)

/tmp/ipykernel_11495/795637831.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Remote Type'].fillna('unknown', inplace=True)

In [ ]:
df["Remote Type"] = df["Remote Type"].str.replace(r"[^a-zA-Z]", ' ', regex=True)

In [ ]:
df["Remote Type"] = df["Remote Type"].str.lower().str.strip().str.replace(' ', '')

In [ ]:
df["Remote Type"].unique()

array(['hybrid', 'unknown', 'na', 'onsite', 'remote', 'wfh', 'hybrd',
       'hybird', 'office', 'workfromhome', 'inoffice', 'hybridwork',
       'fullyremote'], dtype=object)

In [ ]:
mapping = {
    'hybrid': 'Hybrid',
    'unknown': 'Unknown',
    'na': 'Unknown',
    'onsite': 'Onsite',
    'remote': 'Remote',
    'wfh': 'Remote',
    'hybrd': 'Hybrid',
    'hybird': 'Hybrid',
    'office': 'Onsite',
    'workfromhome': 'Remote',
    'inoffice': 'Onsite',
    'hybridwork': 'Hybrid',
    'fullyremote': 'Remote',
    '' : 'Unknown'
}

df["Remote Type"] = df["Remote Type"].map(mapping)

In [ ]:
df["Remote Type"].value_counts()

Remote Type
Remote     3162
Onsite     3080
Hybrid     3079
Unknown     704
Name: count, dtype: int64

Exp. Level -


1.   consistency issues
2.   completeness issues

In [ ]:
df['Exp. Level'].isnull().sum()

np.int64(0)

In [ ]:
df['Exp. Level'].fillna('Unknown', inplace=True)

/tmp/ipykernel_11495/1400856028.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Exp. Level'].fillna('Unknown', inplace=True)

In [ ]:
df['Exp. Level'] = df['Exp. Level'].str.lower()

In [ ]:
df['Exp. Level'].unique()

array(['entry', 'sr', 'mid-level', 'mid', 'junior', 'fresher',
       'senior level', 'senior', 'sr.', 'unknown', 'mid level', 'snr',
       'jr', 'entry level', 'entry-level', 'intermediate', 'na'],
      dtype=object)

In [ ]:
mapping = {
    'entry': 'Junior',
    'sr': 'Senior',
    'mid-level' : 'Mid-level',
    'mid' : 'Mid-level',
    'junior': 'Junior',
    'fresher': 'Fresher',
    'senior level': 'Senior',
    'senior': 'Senior',
    'sr.': 'Senior',
    'unknown' : 'Unknown',
    'mid level': 'Mid-level',
    'snr': 'Senior',
    'jr': 'Junior',
    'entry level': 'Junior',
    'entry-level': 'Junior',
    'intermediate' : 'Mid-level',
    'na':'Unknown'
}

df['Exp. Level'] = df['Exp. Level'].map(mapping)

In [ ]:
df['Exp. Level'].value_counts()

Exp. Level
Senior       3109
Mid-level    3092
Junior       3005
Unknown       684
Fresher       135
Name: count, dtype: int64

Years_Experience -


1.  completeness issue
2.   validity - in some rows experience mentioned in negetive (-8, -9)
3. accuracy - in some records mentioned experience is 999 years
4. mixed - numerical + strings in some records

In [ ]:
df['Years_Experience'].isnull().sum()

np.int64(0)

In [ ]:
df['Years_Experience'] = pd.to_numeric(df['Years_Experience'], errors='coerce')
df['Years_Experience'] = df['Years_Experience'].apply(lambda x: abs(x) if pd.notnull(x) and x < 0 else x)

In [ ]:
df['Years_Experience'] = df['Years_Experience'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)

In [ ]:
df['Years_Experience'] = df['Years_Experience'].fillna(df['Years_Experience'].median())

In [ ]:
df['Years_Experience'] = df['Years_Experience'].replace(999.0, df['Years_Experience'].median())

In [ ]:
df['Years_Experience'].sample(5)

4304     14.3
4036      0.0
10108     6.0
10101     5.0
2370     12.0
Name: Years_Experience, dtype: float64

Education  Level -


1.   completeness issues
2.  consistency issues

In [ ]:
df['Education  Level'].isnull().sum()

np.int64(0)

In [ ]:
df['Education  Level'].fillna('Unknown', inplace=True)

/tmp/ipykernel_11495/629995005.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Education  Level'].fillna('Unknown', inplace=True)

In [ ]:
df['Education  Level'] = df['Education  Level'].str.lower()

In [ ]:
df['Education  Level'].unique()

array(['bachelor', 'batchelor', 'master', 'doctorate', 'phd', 'b.s.',
       'ph.d.', 'maters', 'unknown', 'ms', "master's", 'masterss', 'phd.',
       'ph.d', 'bachelors', "bachelor's", 'bs', 'doctor', 'masters',
       'm.s.', 'p.h.d', 'na'], dtype=object)

In [ ]:
mapping = {
    'bachelor' : "Bachelor's",
    'batchelor': "Bachelor's",
    'master': "Master's",
    'doctorate': 'Ph.D',
    'phd' : 'Ph.D',
    'b.s.': "Bachelor's",
    'ph.d.': 'Ph.D',
    'maters': "Master's",
    'unknown': 'Unknown',
    'ms': "Master's",
    "master's": "Master's",
    'masterss': "Master's",
    'phd.': 'Ph.D',
    'ph.d': 'Ph.D',
    'bachelors': "Bachelor's",
    "bachelor's": "Bachelor's",
    'bs': "Bachelor's",
    'doctor': 'Ph.D',
    'masters': "Master's",
    'm.s.': "Master's",
    'p.h.d': 'Ph.D',
    'na': 'Unknown'
}

In [ ]:
df['Education  Level'] = df['Education  Level'].map(mapping)

In [ ]:
df['Education  Level'].value_counts()

Education  Level
Master's      3157
Ph.D          3072
Bachelor's    3055
Unknown        741
Name: count, dtype: int64

In [ ]:
df.to_csv("new_cleaned_part1.csv", index=False)